In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv(
    "market_data_raw.csv",
    header=[0,1]
)

In [ ]:
data.head()

        Price       Close                                High              \
       Ticker        AAPL        MSFT         SPY        AAPL        MSFT
0        Date         NaN         NaN         NaN         NaN         NaN
1  2021-05-14  124.232132  238.114700  389.078583  124.661025  239.103045
2  2021-05-17  123.081924  235.264816  388.088593  123.725264  236.617799
3  2021-05-18  121.697784  233.249756  384.744904  123.783753  236.445091
4  2021-05-19  121.541817  233.826813  383.736237  121.766005  233.932609

                      Low                                Open              \
          SPY        AAPL        MSFT         SPY        AAPL        MSFT
0         NaN         NaN         NaN         NaN         NaN         NaN
1  389.928511  122.672530  235.562283  385.903047  123.062433  235.648640
2  388.901182  122.009699  233.671958  386.071186  123.618041  236.579423
3  388.592908  121.629552  233.077028  384.586114  123.364609  236.310753
4  383.913696  119.758019  229.479599  378.571312  120.050447  230.162451

                   Volume
          SPY        AAPL        MSFT          SPY
0         NaN         NaN         NaN          NaN
1  385.931065  81918000.0  23901100.0   82201600.0
2  387.967199  74244600.0  24970200.0   65129200.0
3  388.350064  63342900.0  20168000.0   59810200.0
4  380.056370  92612000.0  25739800.0  106467100.0

In [ ]:
data.columns = [
    f"{col[0]}_{col[1]}" if "Unnamed" not in col[0]
    else "Date"
    for col in data.columns
]

In [ ]:
print(data.columns)
data = data.iloc[1:]

Index(['Price_Ticker', 'Close_AAPL', 'Close_MSFT', 'Close_SPY', 'High_AAPL',
       'High_MSFT', 'High_SPY', 'Low_AAPL', 'Low_MSFT', 'Low_SPY', 'Open_AAPL',
       'Open_MSFT', 'Open_SPY', 'Volume_AAPL', 'Volume_MSFT', 'Volume_SPY'],
      dtype='object')

In [ ]:
data.rename(
    columns={"Price_Ticker": "Date"},
    inplace=True
)

In [ ]:
data.head()

,Date,Close_AAPL,Close_MSFT,Close_SPY,High_AAPL,High_MSFT,High_SPY,Low_AAPL,Low_MSFT,Low_SPY,Open_AAPL,Open_MSFT,Open_SPY,Volume_AAPL,Volume_MSFT,Volume_SPY
3,2021-05-18,121.697784,233.249756,384.744904,123.783753,236.445091,388.592908,121.629552,233.077028,384.586114,123.364609,236.310753,388.350064,63342900.0,20168000.0,59810200.0
4,2021-05-19,121.541817,233.826813,383.736237,121.766005,233.932609,383.913696,119.758019,229.479599,378.571312,120.050447,230.162451,380.056370,92612000.0,25739800.0,106467100.0
5,2021-05-20,124.095665,237.058350,387.864471,124.495317,238.472160,389.125354,121.941464,234.538503,384.492806,122.068187,234.634687,384.614200,76857100.0,21800700.0,78022200.0
6,2021-05-21,122.263161,235.798447,387.546844,124.768273,238.837660,390.591638,122.048714,235.384890,387.089202,124.592818,238.106716,389.349425,79295400.0,21863100.0,76578700.0
7,2021-05-24,123.890968,241.194031,391.497620,124.709764,241.559510,392.571694,122.760260,238.049021,389.545570,122.828492,238.318317,389.788415,63092900.0,21411500.0,51376700.0

In [ ]:
data["Date"] = pd.to_datetime(data["Date"])

In [ ]:
data = data.sort_values("Date")

In [ ]:
print(data.isnull().sum())

Date           0
Close_AAPL     0
Close_MSFT     0
Close_SPY      0
High_AAPL      0
High_MSFT      0
High_SPY       0
Low_AAPL       0
Low_MSFT       0
Low_SPY        0
Open_AAPL      0
Open_MSFT      0
Open_SPY       0
Volume_AAPL    0
Volume_MSFT    0
Volume_SPY     0
dtype: int64

In [ ]:
data = data.ffill()

In [ ]:
data.set_index("Date", inplace=True)

In [ ]:
tickers = ["AAPL", "MSFT", "SPY"]

for ticker in tickers:
    data[f"Log_Return_{ticker}"] = np.log(
        data[f"Close_{ticker}"] /
        data[f"Close_{ticker}"].shift(1)
    )

In [ ]:
data.dropna(inplace=True)

In [24]:
data.head()

,Close_AAPL,Close_MSFT,Close_SPY,High_AAPL,High_MSFT,High_SPY,Low_AAPL,Low_MSFT,Low_SPY,Open_AAPL,Open_MSFT,Open_SPY,Volume_AAPL,Volume_MSFT,Volume_SPY,Log_Return_AAPL,Log_Return_MSFT,Log_Return_SPY
Date,,,,,,,,,,,,,,,,,,
2021-05-19,121.541817,233.826813,383.736237,121.766005,233.932609,383.913696,119.758019,229.479599,378.571312,120.050447,230.162451,380.056370,92612000.0,25739800.0,106467100.0,-0.001282,0.002471,-0.002625
2021-05-20,124.095665,237.058350,387.864471,124.495317,238.472160,389.125354,121.941464,234.538503,384.492806,122.068187,234.634687,384.614200,76857100.0,21800700.0,78022200.0,0.020794,0.013726,0.010701
2021-05-21,122.263161,235.798447,387.546844,124.768273,238.837660,390.591638,122.048714,235.384890,387.089202,124.592818,238.106716,389.349425,79295400.0,21863100.0,76578700.0,-0.014877,-0.005329,-0.000819
2021-05-24,123.890968,241.194031,391.497620,124.709764,241.559510,392.571694,122.760260,238.049021,389.545570,122.828492,238.318317,389.788415,63092900.0,21411500.0,51376700.0,0.013226,0.022624,0.010143
2021-05-25,123.696022,242.098083,390.629089,125.080175,243.088711,392.936029,123.130664,241.232492,390.050024,124.592792,242.146175,392.581111,72009500.0,17704300.0,57451400.0,-0.001575,0.003741,-0.002221

In [25]:
data.to_csv("market_data_processed.csv")

In [27]:
from google.colab import files

files.download("market_data_processed.csv")